### PR TITLE
Fixed isProperty function to handle colon as well as space. 

### PR DESCRIPTION
**Pull request by polacojose**
ie. color:black

### CODE REVIEW

**Comment by LinusU** [comment]
Would you mind adding a test as well? Just something that failed before but works now :)

**Comment by LinusU** [comment]
And also, it should support `color: black` (with `: ` as separator)

**Comment by polacojose** [comment]
Yep no problem. :) Adding tests for the other case I've seen accepted  here https://learnboost.github.io/stylus/ as well. 
color :black

**Comment by LinusU** [comment]
Thank you @AustP for getting on this :)

**Comment by AustP** [comment]
@LinusU No problem. Do you have permission to merge by the way?

**Comment by LinusU** [comment]
Yes, I think so :)

**Comment by AustP** [comment]
Ok cool. When I saw this sitting for a few days I wondered if you were waiting for me to merge, which is why I merged it. Now I know. =]

**Pull request merged**
